plugins=()

prehooks() {
	dir=${1}

	ZSH="/usr/share/oh-my-zsh"
	plugins+=(command-not-found history-substring-search web-search)

	hooks ${dir} prehook
}

posthooks() {
	dir=${1}

	hooks ${dir} posthook
}

hooks() {
	dir=${1}
	hook=${2:-hook}

	for f in ${dir}/*; do
		source "${f}"
		if declare -f ${hook} > /dev/null; then
			${hook}
			unset -f ${hook}
		fi
	done
}

main() {
	dirCfg="${1:-${HOME}/.config/zsh}"

	prehooks ${dirCfg}

	source "${ZSH}/oh-my-zsh.sh"

	posthooks ${dirCfg}
}

main ~/.config/zsh

# Path to your oh-my-zsh configuration.
#ZSH=/usr/share/oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="bira"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to  shown in the command execution time stamp 
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
# HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
#plugins=(gpg-agent ssh-agent command-not-found git git-extras git-prompt golang autojump docker history-substring-search docker-compose tmux kubectl npm web-search)

# zstyle :omz:plugins:ssh-agent lifetime 1h

alias whatismyip="curl http://myip.dnsdynamic.org"

function serve() {
	local port=${1:-80}

	docker run --rm -it -p ${port}:80 -v `pwd`:/usr/share/nginx/html nginx:alpine /bin/sh -c "echo 'server { \
    listen 80;
    server_name localhost;
    location / {
      charset utf-8;
      root /usr/share/nginx/html;
      index index.html index.htm;
      autoindex on;
    }
    error_page 500 502 503 504  /50x.html;
    location = /50x.html {
      root /usr/share/nginx/html;
    }
  }' > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
}

# # Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

export WORKON_HOME=~/.virtualenvs
source /usr/bin/virtualenvwrapper_lazy.sh

#PYTHONPATH=/usr/lib/python3.8/site-packages/bb

